name: Feature request
description: Suggest an idea for this project
labels: "Feature Request"
body:
- type: textarea
  attributes:
    label: What feature do you want to see added?
    description: A clear and concise description of your feature request.
  validations:
    required: true
- type: textarea
  attributes:
    label: Are there any alternatives?
    description: List any alternatives you might have tried
  validations:
    required: true
